language: python

branches:
  except:
    - gh-pages

stages:
  - test

jobs:
  include:
  - python: 3.6
    env: TOXENV=check,unit_py3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox "-n $(nproc)"
